// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAF7_TdS6N8hnN32-1ZJ2jUoFjIZbgxiA',
    appId: '1:279778886535:web:e2c52c9306097416b9c922',
    messagingSenderId: '279778886535',
    projectId: 'petcura-95a88',
    authDomain: 'petcura-95a88.firebaseapp.com',
    storageBucket: 'petcura-95a88.appspot.com',
    measurementId: 'G-JN4B4WHR2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxWDMi_AFfKqDgF2oKcsbyljVpoasw8do',
    appId: '1:279778886535:android:588ab38be05c3699b9c922',
    messagingSenderId: '279778886535',
    projectId: 'petcura-95a88',
    storageBucket: 'petcura-95a88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv_3va0M2KglL9Mj-6-evXsNAlggjqi_U',
    appId: '1:279778886535:ios:fd4b09071442d02db9c922',
    messagingSenderId: '279778886535',
    projectId: 'petcura-95a88',
    storageBucket: 'petcura-95a88.appspot.com',
    iosBundleId: 'com.example.testTflite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv_3va0M2KglL9Mj-6-evXsNAlggjqi_U',
    appId: '1:279778886535:ios:0cec298b0d35f87ab9c922',
    messagingSenderId: '279778886535',
    projectId: 'petcura-95a88',
    storageBucket: 'petcura-95a88.appspot.com',
    iosBundleId: 'com.example.testTflite.RunnerTests',
  );
}
